### ISSUE TITLE
Use Mosby for the MVP 

### ISSUE THREAD

**Issue by jjvargas** [artem-zinnatullin/qualitymatters#175] opened 2016-05-18 10:39 UTC
Is it worth using Mosby to replace the MVP part? any advantages or disadvantages?

**Comment by artem-zinnatullin** [comment] 2016-05-18 14:31
Idk, I more like MVVM at the moment (qualitymatters is still MVP though)
¯\_(ツ)_/¯

**Comment by Rainer-Lang** [comment] 2016-05-18 15:42
Why MVVM more than MVP? Could you give some reasons?

**Comment by artem-zinnatullin** [comment] 2016-05-18 15:58
MVVM is Reactive by design.

**Comment by jjvargas** [comment] 2016-05-18 16:17
Any plans to integrate a sample on this project?  or any library you recommend we can use for this?

**Comment by artem-zinnatullin** [comment] 2016-05-18 16:19
Yes, I have plans on migrating project to Kotlin with MVVM (no special
libs).

**Comment by konmik** [comment] 2016-05-18 18:45
Any ideas on flux? It is a much more functional approach than mvvn, especially when you keep "store" immutable.

**Comment by artem-zinnatullin** [comment] 2016-05-18 19:09
No strong opinion about Flux yet.

**Comment by Plastix** [comment] 2016-05-18 21:48
What is flux?

**Comment by konmik** [comment] 2016-05-18 22:08
Flux is a uni-directional architecture developed by Facebook. This name is usually connected with React library for web but it is also considered to be the best UI architecture for usage in functional languages. There is a couple of implementations for Android as well.

**Comment by lenguyenthanh** [comment] 2016-05-19 04:23
@artem-zinnatullin MVVM with RxBinding or Databinding?

**Comment by artem-zinnatullin** [comment] 2016-05-19 06:43
With RxBinding.

**Comment by IgorGanapolsky** [comment] 2016-06-14 21:05
Just an addendum to the OP's question.  I think Mosby would add way too much complexity to this already comprehensive project (which already is using a ton of libraries).  It would confuse the hell out of newbies.  Plus Mosby is not perfect, and is still in formulation by its original creator.

**Comment by artem-zinnatullin** [comment] 2016-07-04 22:43
Closing this. Even though @sockeqwe is a nice guy 😸, I'm personally ok without libraries for design patterns, maybe that'll be changed in future :)

**Closed by artem-zinnatullin** 2016-07-04 22:43 UTC

**Comment by sockeqwe** [comment] 2016-07-04 23:35
👍 
you are a nice guy too  😄
